### ISSUE TITLE
I have error Uncaught RTCError: Transport channel closed

### ISSUE THREAD

**Issue by tresnaa** [coding-with-chaim/group-video-final#2]
when the code running :

**socket.on("receiving returned signal", payload => {**
...

**item.peer.signal(payload.signal);** // i think this line make error

**i found error like this :** 

Uncaught RTCError: Transport channel closed
Uncaught Error: Connection failed.
    at makeError
    at Peer._onConnectionStateChange
    at RTCPeerConnection.Peer._pc.onconnectionstatechange 

Please help me.

Thank you

**Comment by NikolasRoger** [comment]
hi, i fixed that issue inserting this code on the client-side when user joined socket io channel

```

socketRef.current.on("user joined", payload => {
        const item = peersRef.current.find(p => p.peerID === payload.callerID);
        if(!item) {
          const peer = addPeer(payload.signal, payload.callerID, stream);
          peersRef.current.push({
            peerID: payload.callerID,
            peer,
          })
          setPeers(users => [...users, peer]);
        }
});

```

**Comment by tresnaa** [comment]
Thank you @NikolasRoger. The code works for me amazing!!
But, can you tell me, why that code must be inserting?

Thank you.

**Comment by ravi36683** [comment]
Hi @NikolasRoger , @coding-with-chaim 

> hi, i fixed that issue inserting this code on the client-side when user joined socket io channel
> 
> ```
> 
> socketRef.current.on("user joined", payload => {
>         const item = peersRef.current.find(p => p.peerID === payload.callerID);
>         if(!item) {
>           const peer = addPeer(payload.signal, payload.callerID, stream);
>           peersRef.current.push({
>             peerID: payload.callerID,
>             peer,
>           })
>           setPeers(users => [...users, peer]);
>         }
> });
> ```

I've used this code but I'm still getting same error. Can you help me with this ?
![Screenshot 2020-09-27 at 9 21 39 PM](https://user-images.githubusercontent.com/20362429/94369528-dda66300-0107-11eb-9f80-e2e196770ded.png)

Thank you,

**Comment by mukuldeep** [comment]
make sure the peer you are generating during runtime is persistent throughout. Once the page is loaded or state changed, weird errors may be encountered
